import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Visible': 'True', 'Text': 'Layout1', 'Height': '645', 'Width': '405', 'Tag': '', 'Top': '-5', 'Font': '', 'ParentsType': '', 'Name': 'Activity', 'Left': '-10', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Visible': 'True', 'Text': 'Layout1', 'Height': '645', 'Width': '405', 'Tag': '', 'Top': '0', 'Font': '', 'ParentsType': 'Layout', 'Name': 'mBase', 'Left': '0', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'Visible': 'True', 'Text': '', 'Height': '645', 'Width': '405', 'Tag': '', 'Top': '0', 'Font': '', 'ParentsType': 'Layout', 'Name': 'Image1', 'Left': '0', 'BackColor': '(1,1,1,1)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': 'PatientProfile-24703.png', 'ForeColor': '(0,0,0,1)'}","Image","mBase","[]")
		self.btnPrescription=forms
		self.create("{'Visible': 'True', 'Text': '', 'Height': '40', 'Width': '335', 'Tag': '', 'Top': '485', 'Font': '', 'ParentsType': 'Layout', 'Name': 'btnPrescription', 'Left': '35', 'BackColor': '(0, 0.5947705885149066, 0.6256477024706841, 0.5)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Layout","mBase","[]")
		self.btnBack=forms
		self.create("{'Visible': 'True', 'Text': '', 'Height': '40', 'Width': '55', 'Tag': '', 'Top': '10', 'Font': '', 'ParentsType': 'Layout', 'Name': 'btnBack', 'Left': '25', 'BackColor': '(0, 0.5485275470322745, 0.40684617506831855, 0.5)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Layout","mBase","[]")
		self.btnQrReader=forms
		self.create("{'Visible': 'True', 'Text': '', 'Height': '40', 'Width': '55', 'Tag': '', 'Top': '10', 'Font': '', 'ParentsType': 'Layout', 'Name': 'btnQrReader', 'Left': '330', 'BackColor': '(0, 0.5485275470322745, 0.40684617506831855, 0.5)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Layout","mBase","[]")
		self.lblPatientName=forms
		self.create("{'Visible': 'True', 'Text': '', 'Height': '40', 'Width': '230', 'Tag': '', 'Top': '75', 'Font': '', 'ParentsType': 'Layout', 'Alignment': '', 'Name': 'lblPatientName', 'Left': '145', 'BackColor': '(1,1,1,1)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblDesc1=forms
		self.create("{'Visible': 'True', 'Text': '', 'Height': '240', 'Width': '345', 'Tag': '', 'Top': '220', 'Font': '', 'ParentsType': 'Layout', 'Alignment': '', 'Name': 'lblDesc1', 'Left': '30', 'BackColor': '(1,1,1,1)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblAdherence=forms
		self.create("{'Visible': 'True', 'Text': '', 'Height': '25', 'Width': '240', 'Tag': '', 'Top': '120', 'Font': '', 'ParentsType': 'Layout', 'Alignment': '', 'Name': 'lblAdherence', 'Left': '145', 'BackColor': '(1,1,1,1)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblPatientID=forms
		self.create("{'Visible': 'True', 'Text': '', 'Height': '30', 'Width': '240', 'Tag': '', 'Top': '145', 'Font': '', 'ParentsType': 'Layout', 'Alignment': '', 'Name': 'lblPatientID', 'Left': '145', 'BackColor': '(1,1,1,1)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.lblDate1=forms
		self.create("{'Visible': 'True', 'Text': '', 'Height': '30', 'Width': '230', 'Tag': '', 'Top': '190', 'Font': '', 'ParentsType': 'Layout', 'Alignment': '', 'Name': 'lblDate1', 'Left': '145', 'BackColor': '(1,1,1,1)', 'Events': '[[, ]]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.btnMedHistory=forms
		self.create("{'Visible': 'True', 'Text': 'Layout1', 'Height': '40', 'Width': '335', 'Tag': '', 'Top': '545', 'Font': '', 'ParentsType': 'Layout', 'Name': 'btnMedHistory', 'Left': '35', 'BackColor': '(0, 0.5947705885149066, 0.6256477024706841, 0.5)', 'Events': '[]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Layout","mBase","[]")
		self.btnHome=forms
		self.create("{'Visible': 'True', 'Text': 'Layout1', 'Height': '40', 'Width': '70', 'Tag': '', 'Top': '600', 'Font': '', 'ParentsType': 'Layout', 'Name': 'btnHome', 'Left': '140', 'BackColor': '(0, 0.5947705885149066, 0.6256477024706841, 0.5)', 'Events': '[]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Layout","mBase","[]")
		self.btnLogs=forms
		self.create("{'Visible': 'True', 'Text': 'Layout1', 'Height': '40', 'Width': '70', 'Tag': '', 'Top': '600', 'Font': '', 'ParentsType': 'Layout', 'Name': 'btnLogs', 'Left': '210', 'BackColor': '(0, 0.5947705885149066, 0.6256477024706841, 0.5)', 'Events': '[]', 'Var': '', 'Enable': 'True', 'Help': '', 'Picture': '', 'ForeColor': '(0,0,0,1)'}","Layout","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()