import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Var': '', 'Width': '405', 'Events': '[[, ]]', 'Text': 'Layout1', 'Name': 'Activity', 'Tag': '', 'Font': '', 'Height': '620', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '0', 'Left': '0', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Visible': 'True'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '405', 'Events': '[[, ]]', 'Text': 'Layout1', 'Name': 'mBase', 'Tag': '', 'Font': '', 'Height': '620', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '0', 'Left': '0', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)', 'Visible': 'True'}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '405', 'Events': '[[, ]]', 'Text': '', 'Name': 'Image1', 'Tag': '', 'Font': '', 'Height': '620', 'Enable': 'True', 'Picture': 'PatientLogsModule-0beda.png', 'Help': '', 'Top': '0', 'Left': '0', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Image","mBase","[]")
		self.btnHome=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '100', 'Events': '[[, ]]', 'Text': '', 'Name': 'btnHome', 'Tag': '', 'Font': '', 'Height': '45', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '570', 'Left': '0', 'BackColor': '(0, 0.12157566880294246, 0.34919659131927605, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.btnUpdates=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '100', 'Events': '[[, ]]', 'Text': '', 'Name': 'btnUpdates', 'Tag': '', 'Font': '', 'Height': '45', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '570', 'Left': '155', 'BackColor': '(0, 0.12157566880294246, 0.34919659131927605, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.btnProfile=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '75', 'Events': '[[, ]]', 'Text': '', 'Name': 'btnProfile', 'Tag': '', 'Font': '', 'Height': '50', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '5', 'Left': '5', 'BackColor': '(0, 0.12157566880294246, 0.34919659131927605, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.btnQr=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '75', 'Events': '[[, ]]', 'Text': '', 'Name': 'btnQr', 'Tag': '', 'Font': '', 'Height': '50', 'Enable': 'True', 'Picture': '', 'Help': '', 'Top': '5', 'Left': '320', 'BackColor': '(0, 0.12157566880294246, 0.34919659131927605, 0.5)', 'Visible': 'True'}","Layout","mBase","[]")
		self.lblText1=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '290', 'Events': '[[, ]]', 'Text': '', 'Name': 'lblText1', 'Tag': '', 'Font': '', 'Height': '85', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '105', 'Left': '110', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
		self.lblText2=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '290', 'Events': '[[, ]]', 'Text': '', 'Name': 'lblText2', 'Tag': '', 'Font': '', 'Height': '85', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '270', 'Left': '110', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
		self.lblText3=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '290', 'Events': '[[, ]]', 'Text': '', 'Name': 'lblText3', 'Tag': '', 'Font': '', 'Height': '85', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '425', 'Left': '110', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
		self.lbl_dateTime1=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '155', 'Events': '[[, ]]', 'Text': '', 'Name': 'lbl_dateTime1', 'Tag': '', 'Font': '', 'Height': '30', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '75', 'Left': '245', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
		self.lbl_dateTime2=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '155', 'Events': '[[, ]]', 'Text': '', 'Name': 'lbl_dateTime2', 'Tag': '', 'Font': '', 'Height': '30', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '240', 'Left': '245', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
		self.lbl_dateTime3=forms
		self.create("{'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Var': '', 'Width': '155', 'Events': '[[, ]]', 'Text': '', 'Name': 'lbl_dateTime3', 'Tag': '', 'Font': '', 'Height': '30', 'Enable': 'True', 'Alignment': '', 'Picture': '', 'Help': '', 'Top': '395', 'Left': '245', 'BackColor': '(1,1,1,1)', 'Visible': 'True'}","Label","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()