import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.create("{'Font': '', 'Name': 'Activity', 'Text': 'Layout1', 'Help': '', 'Tag': '', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Height': '541', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Top': '-21', 'Width': '362', 'Left': '-8', 'ParentsType': '', 'Var': '', 'Visible': 'True', 'Events': '[[, ]]'}","Layout","usercontrol","[]")
		self.create("{'Font': '', 'Name': 'mBase', 'Text': 'Layout2', 'Help': '', 'Tag': '', 'BackColor': '(1.00,1.00,1.00,1)', 'Height': '525', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Top': '16', 'Width': '305', 'Left': '21', 'ParentsType': 'Layout', 'Var': '', 'Visible': 'True', 'Events': '[[, ]]'}","Layout","Activity","[]")
		self.create("{'Font': '', 'Name': 'Image2', 'Text': 'Image2', 'Help': '', 'Tag': '', 'BackColor': '(1,1,1,1)', 'Height': '73', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'Picture': 'pics1.png', 'Top': '178', 'Width': '132', 'Left': '24', 'ParentsType': 'Layout', 'Var': '', 'Visible': 'True', 'Events': '[[, ]]'}","Image","mBase","[]")
		self.create("{'Font': '', 'Name': 'Image3', 'Text': 'Image3', 'Help': '', 'Tag': '', 'BackColor': '(1,1,1,1)', 'Height': '38', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'Picture': 'pics1.png', 'Top': '122', 'Width': '61', 'Left': '212', 'ParentsType': 'Layout', 'Var': '', 'Visible': 'True', 'Events': '[[, ]]'}","Image","mBase","[]")
		self.create("{'Font': '', 'Name': 'Label2', 'Text': 'Label2', 'Help': '', 'Tag': '', 'BackColor': '(1,1,1,1)', 'Height': '41', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Top': '255', 'Width': '100', 'Left': '25', 'ParentsType': 'Layout', 'Alignment': '', 'Var': '', 'Visible': 'True', 'Events': '[[, ]]'}","Label","mBase","[]")
		self.create("{'Font': '', 'Name': 'ComboBoxText1', 'Text': 'ComboBoxText1', 'Help': '', 'Tag': '', 'BackColor': '(1,1,1,1)', 'Height': '25', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'Picture': '', 'Top': '170', 'Width': '100', 'Left': '175', 'ParentsType': 'Layout', 'Var': '', 'Visible': 'True', 'Events': '[[, ]]'}","ComboBoxText","mBase","[]")
		self.create("{'Font': '', 'Name': 'Timer1', 'Text': 'Timer1', 'Help': '', 'Tag': 'Activex', 'BackColor': '(0, 0.569717995200236, 0.5934507010317029, 0.5)', 'Height': '30', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'Picture': 'Timer.png', 'Top': '210', 'Width': '30', 'Left': '175', 'ParentsType': 'Layout', 'Interval': '1000', 'Var': '', 'Visible': 'True', 'Events': '[[, ]]'}","Timer","mBase","[]")
		self.create("{'AlternateColor': 'False', 'FontStyle': 'Times New Roman', 'Enable': 'True', 'BackColor': '(0, 0.8320927028506803, 0.39714182352662164, 0.5)', 'Height': '75', 'UNSELECT': '#FFFFFF', 'dbtype': '', 'Picture': 'DatagridTreeView.png', 'Width': '125', 'Left': '20', 'Var': '', 'Visible': 'True', 'Font': '', 'Name': 'DatagridTreeView1', 'Help': '', 'FontSize': '14', 'Text': 'DatagridTreeView1', 'ForeColor': '(0,0,0,1)', 'Top': '305', 'Tag': 'Activex', 'ParentsType': 'Layout', 'SELECT': '#FFAAAA', 'Events': '[[, ]]'}","DatagridTreeView","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()