import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.create("{'Text': 'Layout1', 'Picture': '', 'Events': '[[, ]]', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'ForeColor': '(0,0,0,1)', 'Left': '-8', 'Width': '362', 'Font': '', 'Name': 'Activity', 'Tag': '', 'Height': '541', 'ParentsType': '', 'Visible': 'True', 'Top': '-21', 'Enable': 'True', 'Help': '', 'Var': ''}","Layout","usercontrol","[]")
		self.create("{'Text': 'Layout2', 'Picture': '', 'Events': '[[, ]]', 'BackColor': '(1.00,1.00,1.00,1)', 'ForeColor': '(0,0,0,1)', 'Left': '21', 'Width': '305', 'Font': '', 'Name': 'mBase', 'Tag': '', 'Height': '525', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '16', 'Enable': 'True', 'Help': '', 'Var': ''}","Layout","Activity","[]")
		self.create("{'Text': 'Image2', 'Picture': 'pics1.png', 'Events': '[[, ]]', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Left': '24', 'Width': '132', 'Font': '', 'Name': 'imgconnect', 'Tag': '', 'Height': '73', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '93', 'Enable': 'True', 'Help': '', 'Var': ''}","Image","mBase","[]")
		self.create("{'Text': 'Image3', 'Picture': 'pics1.png', 'Events': '[[, ]]', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Left': '182', 'Width': '61', 'Font': '', 'Name': 'imgdisconnect', 'Tag': '', 'Height': '38', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '87', 'Enable': 'True', 'Help': '', 'Var': ''}","Image","mBase","[]")
		self.create("{'Interval': '1000', 'Text': 'Timer1', 'Picture': 'Timer.png', 'Events': '[[, ]]', 'BackColor': '(0, 0.569717995200236, 0.5934507010317029, 0.5)', 'ForeColor': '(0,0,0,1)', 'Left': '175', 'Width': '30', 'Font': '', 'Name': 'Timer1', 'Tag': 'Activex', 'Height': '30', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '210', 'Enable': 'True', 'Help': '', 'Var': ''}","Timer","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()