import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.create("{'Text': 'Layout1', 'Picture': '', 'Events': '[[, ]]', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'ForeColor': '(0,0,0,1)', 'Left': '50', 'Width': '643', 'Font': '', 'Name': 'Activity', 'Tag': '', 'Height': '541', 'ParentsType': '', 'Visible': 'True', 'Top': '30', 'Enable': 'True', 'Help': '', 'Var': ''}","Layout","usercontrol","[]")
		self.create("{'Text': 'Layout2', 'Picture': '', 'Events': '[]', 'BackColor': '(1.00,1.00,1.00,1)', 'ForeColor': '(0,0,0,1)', 'Left': '25', 'Width': '424', 'Font': '', 'Name': 'mBase', 'Tag': '', 'Height': '465', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '15', 'Enable': 'True', 'Help': '', 'Var': ''}","Layout","Activity","[]")
		self.create("{'Text': 'Label1', 'Picture': '', 'Events': '[[, ]]', 'BackColor': '(1,1,1,1)', 'Alignment': '', 'ForeColor': '(0,0,0,1)', 'Left': '35', 'Width': '100', 'Font': '', 'Name': 'Label1', 'Tag': '', 'Height': '30', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '20', 'Enable': 'True', 'Help': '', 'Var': ''}","Label","mBase","[]")
		self.create("{'Text': 'Label2', 'Picture': '', 'Events': '[[, ]]', 'BackColor': '(1,1,1,1)', 'Alignment': '', 'ForeColor': '(0,0,0,1)', 'Left': '165', 'Width': '100', 'Font': '', 'Name': 'Label2', 'Tag': '', 'Height': '30', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '20', 'Enable': 'True', 'Help': '', 'Var': ''}","Label","mBase","[]")
		self.create("{'FontSize': '14', 'Text': 'DatagridTreeView1', 'Left': '35', 'Top': '90', 'Events': '[[, ]]', 'Name': 'DatagridTreeView1', 'Tag': 'Activex', 'Visible': 'True', 'Enable': 'True', 'dbtype': 'sqllite', 'FontStyle': 'Times New Roman', 'Picture': 'DatagridTreeView.png', 'SELECT': '#FFAAAA', 'BackColor': '(0, 0.5771084281161872, 0.6437099811436825, 0.5)', 'UNSELECT': '#FFFFFF', 'ForeColor': '(0,0,0,1)', 'Width': '205', 'Font': '', 'AlternateColor': 'False', 'Height': '160', 'ParentsType': 'Layout', 'Help': '', 'Var': ''}","DatagridTreeView","mBase","[]")
		self.create("{'Interval': '1000', 'Text': 'Timer1', 'Picture': 'Timer.png', 'Events': '[[, ]]', 'BackColor': '(0, 0.3888056493649016, 0.4463967631327912, 0.5)', 'ForeColor': '(0,0,0,1)', 'Left': '285', 'Width': '30', 'Font': '', 'Name': 'Timer1', 'Tag': 'Activex', 'Height': '30', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '130', 'Enable': 'True', 'Help': '', 'Var': ''}","Timer","mBase","[]")
		self.create("{'Interval': '1000', 'Text': 'Timer2', 'Picture': '', 'Events': '[[, ]]', 'BackColor': '(0, 0.12027104030828939, 0.5728644378168872, 0.5)', 'ForeColor': '(0,0,0,1)', 'Left': '195', 'Width': '30', 'Font': '', 'Name': 'mytimer', 'Tag': 'Activex', 'Height': '30', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '280', 'Enable': 'True', 'Help': '', 'Var': ''}","Timer","mBase","[]")
		self.create("{'Text': 'Image1', 'Picture': '', 'Events': '[[, ]]', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Left': '275', 'Width': '100', 'Font': '', 'Name': 'Image1', 'Tag': '', 'Height': '100', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '250', 'Enable': 'True', 'Help': '', 'Var': ''}","Image","mBase","[]")
		self.create("{'Text': 'RadioButton1', 'Picture': '', 'Events': '[]', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Left': '259', 'Width': '80', 'Font': '', 'Name': 'RadioButton1', 'Tag': '', 'Height': '30', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '75', 'Enable': 'True', 'Help': '', 'Var': ''}","RadioButton","mBase","[]")
		self.create("{'Text': 'RadioButton2', 'Picture': '', 'Events': '[]', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Left': '280', 'Width': '80', 'Font': '', 'Name': 'RadioButton2', 'Tag': '', 'Height': '30', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '115', 'Enable': 'True', 'Help': '', 'Var': ''}","RadioButton","mBase","[]")
		self.create("{'Text': 'CheckButton1', 'Picture': '', 'Events': '[]', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Left': '40', 'Width': '80', 'Font': '', 'Name': 'CheckButton1', 'Tag': '', 'Height': '30', 'ParentsType': 'Layout', 'Visible': 'True', 'Top': '260', 'Enable': 'True', 'Help': '', 'Var': ''}","CheckButton","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()