import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Left': '50', 'Text': 'Layout1', 'Enable': 'True', 'Name': 'Activity', 'Events': '[[, ]]', 'Width': '643', 'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Visible': 'True', 'Height': '541', 'Picture': '', 'Help': '', 'Top': '30', 'Font': '', 'Tag': '', 'Var': ''}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'BackColor': '(1.00,1.00,1.00,1)', 'Left': '25', 'Text': 'Layout2', 'Enable': 'True', 'Name': 'mBase', 'Events': '[[, ]]', 'Width': '424', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '465', 'Picture': '', 'Help': '', 'Top': '15', 'Font': '', 'Tag': '', 'Var': ''}","Layout","Activity","[]")
		self.Label1=forms
		self.create("{'BackColor': '(1,1,1,1)', 'Left': '35', 'Text': 'Label1', 'Enable': 'True', 'Name': 'Label1', 'Events': '[[, ]]', 'Width': '100', 'ForeColor': '(0,0,0,1)', 'Alignment': '', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '30', 'Picture': '', 'Help': '', 'Top': '20', 'Font': '', 'Tag': '', 'Var': ''}","Label","mBase","[]")
		self.Label2=forms
		self.create("{'BackColor': '(1,1,1,1)', 'Left': '165', 'Text': 'Label2', 'Enable': 'True', 'Name': 'Label2', 'Events': '[[, ]]', 'Width': '100', 'ForeColor': '(0,0,0,1)', 'Alignment': '', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '30', 'Picture': '', 'Help': '', 'Top': '20', 'Font': '', 'Tag': '', 'Var': ''}","Label","mBase","[]")
		import DatagridTreeView
		self.DatagridTreeView1=DatagridTreeView.Handler
		self.create("{'Left': '35', 'Enable': 'True', 'FontSize': '14', 'ForeColor': '(0,0,0,1)', 'FontStyle': 'Times New Roman', 'SELECT': '#FFAAAA', 'Events': '[[, ]]', 'AlternateColor': 'False', 'Font': '', 'Var': '', 'BackColor': '(0, 0.5771084281161872, 0.6437099811436825, 0.5)', 'Text': 'DatagridTreeView1', 'Name': 'DatagridTreeView1', 'Tag': 'Activex', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '160', 'Picture': 'DatagridTreeView.png', 'UNSELECT': '#FFFFFF', 'Help': '', 'Top': '90', 'Width': '205', 'dbtype': 'sqllite'}","DatagridTreeView","mBase","[]")
		import Timer
		self.Timer1=Timer.Handler
		self.create("{'BackColor': '(0, 0.3888056493649016, 0.4463967631327912, 0.5)', 'Left': '285', 'Text': 'Timer1', 'Enable': 'True', 'Name': 'Timer1', 'Events': '[[, ]]', 'Width': '30', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '30', 'Picture': 'Timer.png', 'Help': '', 'Interval': '1000', 'Top': '130', 'Font': '', 'Tag': 'Activex', 'Var': ''}","Timer","mBase","[]")
		import Timer
		self.mytimer=Timer.Handler
		self.create("{'BackColor': '(0, 0.12027104030828939, 0.5728644378168872, 0.5)', 'Left': '195', 'Text': 'Timer2', 'Enable': 'True', 'Name': 'mytimer', 'Events': '[[, ]]', 'Width': '30', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '30', 'Picture': '', 'Help': '', 'Interval': '1000', 'Top': '280', 'Font': '', 'Tag': 'Activex', 'Var': ''}","Timer","mBase","[]")
		self.Image1=forms
		self.create("{'BackColor': '(1,1,1,1)', 'Left': '275', 'Text': 'Image1', 'Enable': 'True', 'Name': 'Image1', 'Events': '[[, ]]', 'Width': '100', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '100', 'Picture': '', 'Help': '', 'Top': '250', 'Font': '', 'Tag': '', 'Var': ''}","Image","mBase","[]")
		self.RadioButton1=forms
		self.create("{'BackColor': '(1,1,1,1)', 'Left': '259', 'Text': 'RadioButton1', 'Enable': 'True', 'Name': 'RadioButton1', 'Events': '[[, ]]', 'Width': '80', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '30', 'Picture': '', 'Help': '', 'Top': '75', 'Font': '', 'Tag': '', 'Var': ''}","RadioButton","mBase","[]")
		self.RadioButton2=forms
		self.create("{'BackColor': '(1,1,1,1)', 'Left': '280', 'Text': 'RadioButton2', 'Enable': 'True', 'Name': 'RadioButton2', 'Events': '[[, ]]', 'Width': '80', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '30', 'Picture': '', 'Help': '', 'Top': '115', 'Font': '', 'Tag': '', 'Var': ''}","RadioButton","mBase","[]")
		self.CheckButton1=forms
		self.create("{'BackColor': '(1,1,1,1)', 'Left': '40', 'Text': 'CheckButton1', 'Enable': 'True', 'Name': 'CheckButton1', 'Events': '[[, ]]', 'Width': '80', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Visible': 'True', 'Height': '30', 'Picture': '', 'Help': '', 'Top': '260', 'Font': '', 'Tag': '', 'Var': ''}","CheckButton","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()