import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.create("{'Visible': 'True', 'Name': 'Activity', 'ParentsType': '', 'Left': '50', 'Picture': '', 'Width': '643', 'Font': '', 'Text': 'Layout1', 'Tag': '', 'Events': '[[, ]]', 'Var': '', 'Top': '30', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Help': '', 'Enable': 'True', 'Height': '541', 'ForeColor': '(0,0,0,1)'}","Layout","usercontrol","[]")
		self.create("{'Visible': 'True', 'Name': 'mBase', 'ParentsType': 'Layout', 'Left': '25', 'Picture': '', 'Width': '424', 'Font': '', 'Text': 'Layout2', 'Tag': '', 'Events': '[[, ]]', 'Var': '', 'Top': '15', 'BackColor': '(1.00,1.00,1.00,1)', 'Help': '', 'Enable': 'True', 'Height': '465', 'ForeColor': '(0,0,0,1)'}","Layout","Activity","[]")
		self.create("{'Visible': 'True', 'Name': 'Label1', 'ParentsType': 'Layout', 'Left': '35', 'Picture': '', 'Alignment': '', 'Width': '100', 'Font': '', 'Text': 'Label1', 'Tag': '', 'Events': '[[, ]]', 'Var': '', 'Top': '20', 'BackColor': '(1,1,1,1)', 'Help': '', 'Enable': 'True', 'Height': '30', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.create("{'Visible': 'True', 'Name': 'Label2', 'ParentsType': 'Layout', 'Left': '165', 'Picture': '', 'Alignment': '', 'Width': '100', 'Font': '', 'Text': 'Label2', 'Tag': '', 'Events': '[[, ]]', 'Var': '', 'Top': '20', 'BackColor': '(1,1,1,1)', 'Help': '', 'Enable': 'True', 'Height': '30', 'ForeColor': '(0,0,0,1)'}","Label","mBase","[]")
		self.create("{'UNSELECT': '#FFFFFF', 'Visible': 'True', 'Name': 'DatagridTreeView1', 'Help': '', 'ForeColor': '(0,0,0,1)', 'FontSize': '14', 'SELECT': '#FFAAAA', 'Width': '205', 'Font': '', 'Tag': 'Activex', 'Events': '[[, ]]', 'BackColor': '(0, 0.5771084281161872, 0.6437099811436825, 0.5)', 'Top': '90', 'dbtype': 'sqllite', 'Height': '160', 'Text': 'DatagridTreeView1', 'Left': '35', 'Picture': 'DatagridTreeView.png', 'FontStyle': 'Times New Roman', 'Var': '', 'ParentsType': 'Layout', 'Enable': 'True', 'AlternateColor': 'False'}","DatagridTreeView","mBase","[]")
		self.create("{'Visible': 'True', 'Name': 'Timer1', 'ParentsType': 'Layout', 'Left': '285', 'Picture': 'Timer.png', 'Width': '30', 'Font': '', 'Text': 'Timer1', 'Tag': 'Activex', 'Interval': '1000', 'Events': '[[, ]]', 'Var': '', 'Top': '130', 'BackColor': '(0, 0.3888056493649016, 0.4463967631327912, 0.5)', 'Help': '', 'Enable': 'True', 'Height': '30', 'ForeColor': '(0,0,0,1)'}","Timer","mBase","[]")
		self.create("{'Visible': 'True', 'Name': 'mytimer', 'ParentsType': 'Layout', 'Left': '195', 'Picture': '', 'Width': '30', 'Font': '', 'Text': 'Timer2', 'Tag': 'Activex', 'Interval': '1000', 'Events': '[[, ]]', 'Var': '', 'Top': '280', 'BackColor': '(0, 0.12027104030828939, 0.5728644378168872, 0.5)', 'Help': '', 'Enable': 'True', 'Height': '30', 'ForeColor': '(0,0,0,1)'}","Timer","mBase","[]")
		self.create("{'Visible': 'True', 'Name': 'Image1', 'ParentsType': 'Layout', 'Left': '275', 'Picture': '', 'Width': '100', 'Font': '', 'Text': 'Image1', 'Tag': '', 'Events': '[[, ]]', 'Var': '', 'Top': '250', 'BackColor': '(1,1,1,1)', 'Help': '', 'Enable': 'True', 'Height': '100', 'ForeColor': '(0,0,0,1)'}","Image","mBase","[]")
		self.create("{'Visible': 'True', 'Name': 'RadioButton1', 'ParentsType': 'Layout', 'Left': '259', 'Picture': '', 'Width': '80', 'Font': '', 'Text': 'RadioButton1', 'Tag': '', 'Events': '[[, ]]', 'Var': '', 'Top': '75', 'BackColor': '(1,1,1,1)', 'Help': '', 'Enable': 'True', 'Height': '30', 'ForeColor': '(0,0,0,1)'}","RadioButton","mBase","[]")
		self.create("{'Visible': 'True', 'Name': 'RadioButton2', 'ParentsType': 'Layout', 'Left': '280', 'Picture': '', 'Width': '80', 'Font': '', 'Text': 'RadioButton2', 'Tag': '', 'Events': '[[, ]]', 'Var': '', 'Top': '115', 'BackColor': '(1,1,1,1)', 'Help': '', 'Enable': 'True', 'Height': '30', 'ForeColor': '(0,0,0,1)'}","RadioButton","mBase","[]")
		self.create("{'Visible': 'True', 'Name': 'CheckButton1', 'ParentsType': 'Layout', 'Left': '40', 'Picture': '', 'Width': '80', 'Font': '', 'Text': 'CheckButton1', 'Tag': '', 'Events': '[[, ]]', 'Var': '', 'Top': '260', 'BackColor': '(1,1,1,1)', 'Help': '', 'Enable': 'True', 'Height': '30', 'ForeColor': '(0,0,0,1)'}","CheckButton","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()