import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Top': '30', 'Left': '55', 'Height': '541', 'Enable': 'True', 'ForeColor': '(1,1,1,1)', 'ParentsType': '', 'Width': '643', 'Var': '', 'Font': '', 'Name': 'Activity', 'Visible': 'True', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Layout1'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Top': '5', 'Left': '20', 'Height': '465', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Width': '424', 'Var': '', 'Font': '', 'Name': 'mBase', 'Visible': 'True', 'BackColor': '(1.00,1.00,1.00,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Layout2'}","Layout","Activity","[]")
		self.p_Home=forms
		self.create("{'Top': '415', 'Left': '0', 'Height': '50', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Width': '140', 'Var': '', 'Font': '', 'Name': 'p_Home', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Home'}","Button","mBase","[]")
		self.p_Updates=forms
		self.create("{'Top': '450', 'Left': '215', 'Height': '50', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Width': '145', 'Var': '', 'Font': '', 'Name': 'p_Updates', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Updates'}","Button","usercontrol","[]")
		self.p_Logs=forms
		self.create("{'Top': '450', 'Left': '360', 'Height': '50', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Width': '140', 'Var': '', 'Font': '', 'Name': 'p_Logs', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Logs'}","Button","usercontrol","[]")
		self.Frame1=forms
		self.create("{'Top': '25', 'Left': '75', 'Height': '55', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Width': '425', 'Var': '', 'Font': '', 'Name': 'Frame1', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': ''}","Frame","usercontrol","[]")
		self.p_Profile=forms
		self.create("{'Top': '15', 'Left': '15', 'Height': '35', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Frame', 'Width': '100', 'Var': '', 'Font': '', 'Name': 'p_Profile', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Profile'}","Button","Frame1","[]")
		self.p_Qr=forms
		self.create("{'Top': '40', 'Left': '395', 'Height': '35', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Width': '100', 'Var': '', 'Font': '', 'Name': 'p_Qr', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'QR Code'}","Button","usercontrol","[]")
		self.p_User=forms
		self.create("{'Top': '55', 'Left': '0', 'Height': '35', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Alignment': '', 'Width': '424', 'Var': '', 'Font': '', 'Name': 'p_User', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': ''}","Label","mBase","[]")
		self.p_Overview=forms
		self.create("{'Top': '95', 'Left': '0', 'Height': '30', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Width': '212', 'Var': '', 'Font': '', 'Name': 'p_Overview', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Overview'}","Button","mBase","[]")
		self.p_Schedule=forms
		self.create("{'Top': '130', 'Left': '285', 'Height': '30', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Width': '214', 'Var': '', 'Font': '', 'Name': 'p_Schedule', 'Visible': 'False', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Schedule'}","Button","usercontrol","[]")
		self.label2=forms
		self.create("{'Top': '130', 'Left': '0', 'Height': '20', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Alignment': 'CENTER', 'Width': '425', 'Var': '', 'Font': '', 'Name': 'label2', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Categories'}","Label","mBase","[]")
		self.p_Medications=forms
		self.create("{'Top': '155', 'Left': '0', 'Height': '35', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Width': '140', 'Var': '', 'Font': '', 'Name': 'p_Medications', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Medications'}","Button","mBase","[]")
		self.p_Appointments=forms
		self.create("{'Top': '190', 'Left': '215', 'Height': '35', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Width': '145', 'Var': '', 'Font': '', 'Name': 'p_Appointments', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Appointments'}","Button","usercontrol","[]")
		self.p_Hotlines=forms
		self.create("{'Top': '190', 'Left': '360', 'Height': '35', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': '', 'Width': '140', 'Var': '', 'Font': '', 'Name': 'p_Hotlines', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Hotlines'}","Button","usercontrol","[]")
		self.p_Map=forms
		self.create("{'Top': '215', 'Left': '0', 'Height': '190', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Width': '425', 'Var': '', 'Font': '', 'Name': 'p_Map', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': ''}","Frame","mBase","[]")
		self.Label1=forms
		self.create("{'Top': '200', 'Left': '0', 'Height': '30', 'Enable': 'True', 'ForeColor': '(0,0,0,1)', 'ParentsType': 'Layout', 'Alignment': 'CENTER', 'Width': '425', 'Var': '', 'Font': '', 'Name': 'Label1', 'Visible': 'True', 'BackColor': '(1,1,1,1)', 'Events': '[]', 'Help': '', 'Tag': '', 'Picture': '', 'Text': 'Healthcare Providers Near You'}","Label","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()