import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'Var': '', 'Text': 'Layout1', 'ParentsType': '', 'Height': '655', 'Left': '5', 'Tag': '', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'ForeColor': '(0,0,0,1)', 'Name': 'Activity', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Width': '405', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '5'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'Var': '', 'Text': 'Layout1', 'ParentsType': 'Layout', 'Height': '655', 'Left': '0', 'Tag': '', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)', 'ForeColor': '(0,0,0,1)', 'Name': 'mBase', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Width': '405', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '0'}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '655', 'Left': '0', 'Tag': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Name': 'Image1', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': 'HomeModule-5ae79.png', 'Width': '405', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '0'}","Image","mBase","[]")
		self.btnProfile=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '45', 'Left': '20', 'Tag': '', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)', 'ForeColor': '(0,0,0,1)', 'Name': 'btnProfile', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Width': '55', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '5'}","Layout","mBase","[]")
		self.btnQrReader=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '45', 'Left': '332', 'Tag': '', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)', 'ForeColor': '(0,0,0,1)', 'Name': 'btnQrReader', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Width': '55', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '7'}","Layout","mBase","[]")
		self.btnSchedule=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '35', 'Left': '217', 'Tag': '', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)', 'ForeColor': '(0,0,0,1)', 'Name': 'btnSchedule', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Width': '160', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '142'}","Layout","mBase","[]")
		self.btnContact=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '35', 'Left': '220', 'Tag': '', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)', 'ForeColor': '(0,0,0,1)', 'Name': 'btnContact', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Width': '150', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '292'}","Layout","mBase","[]")
		self.btnLogs=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '45', 'Left': '200', 'Tag': '', 'BackColor': '(0, 0.5070987989932315, 0.14762284075298326, 0.5)', 'ForeColor': '(0,0,0,1)', 'Name': 'btnLogs', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Width': '70', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '607'}","Layout","mBase","[]")
		self.lblName=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '65', 'Left': '20', 'Tag': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Name': 'lblName', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Alignment': '', 'Width': '355', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '70'}","Label","mBase","[]")
		self.lblProgress=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '75', 'Left': '35', 'Tag': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Name': 'lblProgress', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Alignment': '', 'Width': '335', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '215'}","Label","mBase","[]")
		self.d_Notif1=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '75', 'Left': '100', 'Tag': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Name': 'd_Notif1', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Alignment': '', 'Width': '260', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '390'}","Label","mBase","[]")
		self.d_Notif2=forms
		self.create("{'Var': '', 'Text': '', 'ParentsType': 'Layout', 'Height': '75', 'Left': '100', 'Tag': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Name': 'd_Notif2', 'Events': '[[, ]]', 'Enable': 'True', 'Picture': '', 'Alignment': '', 'Width': '260', 'Help': '', 'Visible': 'True', 'Font': '', 'Top': '485'}","Label","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()