import gi
import time
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk,GObject,Gdk,Pango,GLib
from wta_module import *
#	Generated By WiredGTK for Python: by Rocky Nuarin, 2018 Phils
#	#####################www.WireThemAll.com#####################

class Handler(object):
	def __init__(self,*param):			
		initUI(self,param,w=400,h=400,title="WiredGTKV1.0",controlbox=True,startpos=(200,200),timeoutdestroy=-1)
		self.GTKForms()
		self.sch=Scheduler(500)#500 ms
		self.sch.Start()

	def unload(self,*args):
		destroy=True
		if destroy==True:
			GLib.source_remove(self.timeout_id)
			self._window.hide()
			del self._window
			#ExitApplication() #activate this if u want to destroy this window
			return False
		else:
			self.window.Visible=False
			return True		
	def loop(self, user_data):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					self.unload(None)
			self.sch.Start()#restart scheduler
		return True	#return true so that main_loop can call it again 
	def create(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)
	def GTKForms(self):
		self.Activity=forms
		self.create("{'ParentsType': '', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(0, 0.15818675032557372, 0.9408383013784336, 0.5)', 'ForeColor': '(0,0,0,1)', 'Width': '370', 'Picture': '', 'Left': '5', 'Text': 'Layout1', 'Height': '655', 'Name': 'Activity', 'Top': '5', 'Events': '[[, ]]'}","Layout","usercontrol","[]")
		self.mBase=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(0, 0.9535890512821091, 0.7790916597141007, 0.5)', 'ForeColor': '(0,0,0,1)', 'Width': '370', 'Picture': '', 'Left': '0', 'Text': 'Layout1', 'Height': '655', 'Name': 'mBase', 'Top': '0', 'Events': '[[, ]]'}","Layout","Activity","[]")
		self.Image1=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Width': '370', 'Picture': 'ProfileSubModule-42864.png', 'Left': '0', 'Text': '', 'Height': '655', 'Name': 'Image1', 'Top': '0', 'Events': '[[, ]]'}","Image","mBase","[]")
		self.btnLogout=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(0, 0.7406073418126649, 0.09054132530882697, 0.5)', 'ForeColor': '(0,0,0,1)', 'Width': '120', 'Picture': '', 'Left': '125', 'Text': '', 'Height': '40', 'Name': 'btnLogout', 'Top': '605', 'Events': '[[, ]]'}","Layout","mBase","[]")
		self.btnQr=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(0, 0.09798044860069444, 0.1712494341186408, 0.5)', 'ForeColor': '(0,0,0,1)', 'Width': '45', 'Picture': '', 'Left': '305', 'Text': '', 'Height': '40', 'Name': 'btnQr', 'Top': '10', 'Events': '[[, ]]'}","Layout","mBase","[]")
		self.btnBack=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(0, 0.5700095957594278, 0.8007551983979785, 0.5)', 'ForeColor': '(0,0,0,1)', 'Width': '45', 'Picture': '', 'Left': '15', 'Text': '', 'Height': '40', 'Name': 'btnBack', 'Top': '10', 'Events': '[[, ]]'}","Layout","mBase","[]")
		self.lblName=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'False', 'Font': '', 'Var': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Width': '310', 'Picture': '', 'Left': '30', 'Text': '', 'Height': '55', 'Name': 'lblName', 'Top': '235', 'Events': '[[, ]]', 'Alignment': 'CENTER'}","Label","mBase","[]")
		self.lbl_ID=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Width': '320', 'Picture': '', 'Left': '25', 'Text': '', 'Height': '30', 'Name': 'lbl_ID', 'Top': '370', 'Events': '[[, ]]', 'Alignment': 'CENTER'}","Label","mBase","[]")
		self.lblAddress=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Width': '320', 'Picture': '', 'Left': '25', 'Text': '', 'Height': '30', 'Name': 'lblAddress', 'Top': '430', 'Events': '[[, ]]', 'Alignment': ''}","Label","mBase","[]")
		self.lblCounty=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Width': '135', 'Picture': '', 'Left': '25', 'Text': '', 'Height': '25', 'Name': 'lblCounty', 'Top': '485', 'Events': '[[, ]]', 'Alignment': ''}","Label","mBase","[]")
		self.lblZip=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Width': '150', 'Picture': '', 'Left': '195', 'Text': '', 'Height': '25', 'Name': 'lblZip', 'Top': '485', 'Events': '[[, ]]', 'Alignment': ''}","Label","mBase","[]")
		self.lblState=forms
		self.create("{'ParentsType': 'Layout', 'Tag': '', 'Help': '', 'Visible': 'True', 'Enable': 'True', 'Font': '', 'Var': '', 'BackColor': '(1,1,1,1)', 'ForeColor': '(0,0,0,1)', 'Width': '320', 'Picture': '', 'Left': '25', 'Text': '', 'Height': '30', 'Name': 'lblState', 'Top': '535', 'Events': '[[, ]]', 'Alignment': 'CENTER'}","Label","mBase","[]")
	def Widget(self):
		if self._usercontrol in self._mainlayout.get_children():
			self._mainlayout.remove(self._usercontrol)
		return self._usercontrol
	def Hide(self):
		self._window.hide()
	def Show(self,modal=False,x=None,y=None):
		if x!=None:
			self._window.move(x,y)
		self._window.set_modal(modal)
		self._window.show()
		Gtk.main()
		return ""#put ur return value here upon closing this form
if __name__ == "__main__":
	_m = Handler()
	_m._window.show()
	Gtk.main()